<a href="https://colab.research.google.com/github/RishithaSrija/Python_libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TaskArray creation

In [135]:
arr1=np.arange(10,51)
print(arr1)
ran_arr=np.random.random((3,3))
print(ran_arr)
#1
print("Array:",end='\n')
print("Shape: ",arr1.shape)
print("Size: ",arr1.size)
print("Data type: ",arr1.dtype)
print("Random Array:")
print("Shape: ",ran_arr.shape)
print("Size: ",ran_arr.size)
print("Data type: ",ran_arr.dtype)
print()
#2
print(arr1+5)
arr2=np.array([[1,2,3],[8,9,7]])
arr3=np.array([[3,4,2],[7,5,4]])
print(arr2)
print(arr3)
print()
#3
arr5=np.arange(1,26).reshape(5,5)
print(arr5)
print(arr5[0])
print(arr5[4])
print("Subarray: first 3 rows and first 2 columns: ",arr5[0:4,0:3])
#4
arr6=np.random.randint(10,101,size=10)
print(arr6)
print("Maximum:",arr6.max())
print("Minimum:",arr6.min())
print("Mean:",arr6.mean())
print("Standard Deviation:",arr6.std())

#5

n_ar=np.array([range(1,13)])
print("Reshape: ",n_ar.reshape(3,4))

#6
n_one=np.ones((3,3))
print("Add [1,2,3] to each row:",n_one[:,:]+[1,2,3])
print()
#7
arr7=np.random.randint(1,51,size=15)
print("Integers divisible by 5 from 1 to 50:",arr7[arr7%5==0])
#8
m=np.array([[3,2],[4,3]])
n=np.array([[90,7],[6,87]])
print("Matrix multiplication",m*n)
#9
arr8=np.arange(1,17).reshape(4,4)
# print("Diagonal elements:",arr8.diag(arr8))
diag = arr8[np.arange(arr8.shape[0]), np.arange(arr8.shape[1])]
print("Diagonal elements:",diag)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.80480766 0.37452711 0.43413174]
 [0.68727155 0.63169584 0.96425914]
 [0.24440585 0.55142788 0.88754497]]
Array:
Shape:  (41,)
Size:  41
Data type:  int64
Random Array:
Shape:  (3, 3)
Size:  9
Data type:  float64

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[1 2 3]
 [8 9 7]]
[[3 4 2]
 [7 5 4]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[21 22 23 24 25]
Subarray: first 3 rows and first 2 columns:  [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[13 78 70 26 54 15 59 28 22 18]
Maximum: 78
Minimum: 13
Mean: 38.3
Standard Deviation: 23.182105167564053
Reshape:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Add [1,2,3] to each row: [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]

Integers divisible by 5 from 1 to 50: [40 20 40]
Matr

# Numpy


In [1]:
import numpy as np
arr_np=np.array([1,2,3,4,5])
print(arr_np)

[1 2 3 4 5]


In [109]:
import numpy as np
arr_np1=np.array([[1,2,3],[4,5,6]])
print(arr_np1)
print(arr_np1.shape)
print(arr_np1.dtype)
print()
np.save('array.npy',arr_np1)
loaded_arr=np.load('array.npy')
print(loaded_arr)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64

[[1 2 3]
 [4 5 6]]


In [107]:
arr=np.array([1,2,34,56,78,9])
reshaped=arr.reshape(2,3)
print(reshaped)
#view-shares the memory
arr=np.array([1,2,3])
view=arr.view()
print(view)
view[0]=4
print(view)
print(arr)
print()
#copy -do not share the memory
arr=np.array([1,2,3])
copy=arr.copy()
print(copy)
copy[0]=74
print(copy)
print(arr)

[[ 1  2 34]
 [56 78  9]]
[1 2 3]
[4 2 3]
[4 2 3]

[1 2 3]
[74  2  3]
[1 2 3]


In [104]:
m=np.array([1,4,6])
n=np.array([2,5,7])
#stacking
print("Vertical stack:",np.vstack((m,n)))
print("Horizontal stack:",np.hstack((m,n)))
print("Column stack:",np.column_stack((m,n)))
#splitting

print("Splitting into parts:",np.array_split(m,2))
indices=[0,2]
print(arr[indices])

Vertical stack: [[1 4 6]
 [2 5 7]]
Horizontal stack: [1 4 6 2 5 7]
Column stack: [[1 2]
 [4 5]
 [6 7]]
Splitting into parts: [array([1, 4]), array([6])]
[ 1 34]


# Data Engineer


In [37]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data Type:",temp_data.dtype)
print("Dimension:",temp_data.ndim)

gh3=np.array([21,23,22])
update_temp_data=np.vstack((temp_data,gh3))
print(update_temp_data)

sensor_array_flags=np.zeros((2,3))
print(sensor_array_flags)
greenhouse_identity=np.eye(3,3)
print(greenhouse_identity)


[[22 25 20]
 [24 26 23]]
Shape: (2, 3)
Size: 6
Data Type: int64
Dimension: 2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
ar=np.array([[23,32,2],[5,54,565]])
print(ar[1,1])
print(ar[1,-3])
print(np.sort(ar))
print(ar[:,1:])
arr=np.array([[[1,2,3,11],[4,5,6,21]],
              [[34,45,56,12],[66,43,67,21]]])
print(arr[:,1,:])

54
5
[[  2  23  32]
 [  5  54 565]]
[[ 32   2]
 [ 54 565]]
[[ 4  5  6 21]
 [66 43 67 21]]


#Data Analyst

In [55]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)

print("Apples shipped on Wednesday:",shipments[0,2])
print("Oranges shipped on Sunday:",shipments[1,6])
print("Mon-Fri all fruits",shipments[:,0:5])
print("Weekend shipments:",shipments[:,5:7])
print("Apples from wed to sat:",shipments[0,2:6])
shipments[0][5]=100
print("Replaced the saturday shipment of apples with 100 using indexing",shipments)


[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
Apples shipped on Wednesday: 55
Oranges shipped on Sunday: 75
Mon-Fri all fruits [[50 60 55 70 65]
 [40 45 50 60 55]]
Weekend shipments: [[80 90]
 [70 75]]
Apples from wed to sat: [55 70 65 80]
Replaced the saturday shipment of apples with 100 using indexing [[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [73]:
m=np.array([2,6,9])
n=np.array([7,6,5])
print("Addition:",m+n)
print("Multiplication:",m*n)
print("Scalar operations:",n*5,n+3)

ar=np.array([[23,32,2],[5,54,565]])
arr=np.array([[1,2,3,11],[4,5,6,21],
             [66,43,67,21]])
print(np.dot(ar,arr))
print(np.exp(ar))
print()
print(np.sqrt(arr))
print()
print(np.log(arr))
print(np.expm1(ar))
print()
print(np.log1p(arr))
print()
print(np.sin(ar))
print(np.arctan(ar))
print(np.degrees(ar))
print()
# x = np.array([True, False, True, False])
# y = np.array([True, True, False, False])

# print(np.logical_and(x, y))
print(np.logical_xor(m, n))
print(np.invert(m,n))
print(np.bitwise_or(m,n))
print(np.equal(m,n))



Addition: [ 9 12 14]
Multiplication: [14 36 45]
Scalar operations: [35 30 25] [10  9  8]
[[  283   292   395   967]
 [37511 24575 38194 13054]]
[[9.74480345e+009 7.89629602e+013 7.38905610e+000]
 [1.48413159e+002 2.83075330e+023 2.37893335e+245]]

[[1.         1.41421356 1.73205081 3.31662479]
 [2.         2.23606798 2.44948974 4.58257569]
 [8.1240384  6.55743852 8.18535277 4.58257569]]

[[0.         0.69314718 1.09861229 2.39789527]
 [1.38629436 1.60943791 1.79175947 3.04452244]
 [4.18965474 3.76120012 4.20469262 3.04452244]]
[[9.74480345e+009 7.89629602e+013 6.38905610e+000]
 [1.47413159e+002 2.83075330e+023 2.37893335e+245]]

[[0.69314718 1.09861229 1.38629436 2.48490665]
 [1.60943791 1.79175947 1.94591015 3.09104245]
 [4.20469262 3.78418963 4.21950771 3.09104245]]

[[-0.8462204   0.55142668  0.90929743]
 [-0.95892427 -0.55878905 -0.46769187]]
[[1.52734543 1.53955649 1.10714872]
 [1.37340077 1.55227992 1.56902642]]
[[ 1317.8029288   1833.46494442   114.59155903]
 [  286.47889757  30

# Data Engineer (renewable-energy)


In [2]:
import numpy as np

farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
#1
production_al1=np.array([farmA,farmB,farmC])
print(production_al1)
print()
#2
print(production_al1.shape)
print(production_al1.size)
print(production_al1.ndim)
print(production_al1.dtype)
#3
tot_per_farm=np.sum(production_al1,axis=(1,2))
print(tot_per_farm)
print(tot_per_farm.shape)
mean_per_farm = np.mean(production_al1, axis=(1, 2))
std_per_farm = np.std(production_al1, axis=(1, 2))
var_per_farm = np.var(production_al1, axis=(1, 2))

print("Mean per farm:", mean_per_farm)
print("Standard deviation per farm:", std_per_farm)
print("Variance per farm:", var_per_farm)

#4
hours_wt=np.array([0.5,1.0,0.75])
weight_per_panel=np.dot(production_al1,hours_wt)
print("dot product  between each farm's panel-row and hours_wt:",weight_per_panel)

#5
addition = np.zeros_like(production_al1, dtype=float)
addition[1,:,:]=0.5
production_al1=production_al1+addition
print(production_al1)

#6
sub=np.zeros_like(production_al1,dtype=float)
sub[:,:,:]=mean_per_farm
production_al1=production_al1-sub
print("subtract the per-farm mean (use broadcasting):",production_al1)
print()
div=np.zeros_like(production_al1,dtype=float)
div[:,:,:]=production_al1/std_per_farm[:,np.newaxis,np.newaxis]
print("After dividing by the per-farm std (z-score normalized broadcasting):",production_al1)
print()




[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]

(3, 4, 3)
36
3
int64
[126 234 174]
(3,)
Mean per farm: [10.5 19.5 14.5]
Standard deviation per farm: [1.97905701 1.97905701 1.97905701]
Variance per farm: [3.91666667 3.91666667 3.91666667]
dot product  between each farm's panel-row and hours_wt: [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]
subtract the per-farm mean (use broadcasting): [[[ -0.5  -7.5  -3.5]
  [ -1.5  -8.5  -4.5]
  [  1.5  -6.5  -0.5]
  [ -2.5 -12.5  -5.5]]

 [[ 10.    0.    7. ]
  [  8.    1.    5. ]
  [ 12.    4.    7. ]
  [  7.   -1.    2. ]]

 [[  4.5  -3.5  -0.5]
  [  3.5  -6.5   0.5]
  [

In [14]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_al=np.array([farmA,farmB,farmC])
print(production_al)
print("Shape of production data:", production_al.shape)
print()
#exponential and logarithmic functions
exp_data=np.exp(production_al)
expm1_data=np.expm1(production_al)

log_data=np.log(production_al)
log10_data=np.log10(production_al)
log2_data=np.log2(production_al)
print("Exponential family results:")
print("exp-> shape:",exp_data.shape,", dtype: ",exp_data.dtype)
print("exmp1 -> first row:\n ",expm1_data[0])
print("log -> first row:\n ",log_data[0])
print("log10 -> first row:\n ",log10_data[0])
print("log2 -> first row:\n ",log2_data[0])

#trignometric fun
sin_data=np.sin(production_al)
cos_data=np.cos(production_al)
tan_data=np.tan(production_al)

clipped=np.clip(production_al,-1,1)
arcsin_data=np.arcsin(clipped)
arccos_data=np.arccos(clipped)
arctan_data=np.arctan(clipped)

deg_data=np.degrees(production_al)
rad_data=np.radians(production_al)

print("Trigonometric family results:")
print("cos -> first row:\n ",cos_data[0])
print("arctan (in degrees) -> first row:\n", deg_data[0])
print()

#Rounding funs
round_data=np.round(production_al/3.3,2)
floor_data=np.floor(production_al/3.3)
trunc_data=np.trunc(production_al/3.3)
print("Round: ",round_data[0][0])
print("Floor: ",floor_data[0][0])
print("Trunc: ",trunc_data[0][0])

high_output=production_al>20

even_hr_mask=(np.arange(production_al.shape[2])%2==0)
even_hr_mask=np.tile(even_hr_mask,(production_al.shape[0], production_al.shape[1], 1))

and_mask=np.logical_and(high_output,even_hr_mask)

not_mask=np.logical_not(high_output)
print("Logical mask examples (Farm B first row):")
print("High output mask:\n", high_output[1][0])
print("Even hours mask:\n", even_hr_mask[1][0])
print("AND mask:\n", not_mask[1][0])
print()

grt_eq_mask=np.greater_equal(production_al,20)
less_eq_mask=np.less(production_al,15)

print("Comparison ufuncs examples:")
print("Greater or equal to 15 (Farm C first row):", grt_eq_mask[2][0])
print("Less than 10 (Farm A first row):", less_eq_mask[0][0])
print()

alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]
])
bit_and = np.bitwise_and(production_al.astype(int) > 18, alerts)
bit_or  = np.bitwise_or(production_al.astype(int) > 18, alerts)
bit_not = np.invert(alerts.astype(bool))

print("Bitwise operations examples (Farm B first row):")
print("Bitwise AND:\n", bit_and[1][0])
print("Bitwise OR:\n", bit_or[1][0])
print("Bitwise NOT (on alerts):\n", bit_not[1][0])
print()

#Arithmetic funs
add_data=np.add(production_al,10)
divided=np.divide(farmB,(farmA+1))
power=np.power(farmA,2)
modulus=np.mod(farmC,2)

print("Addition :",add_data)
print("Divison: ",divided)
print("Power: ",power)
print("Modulus: ",modulus)

#Aggregate ufunc
sum_exp = np.sum(np.exp(production_al))
mean_sin = np.mean(np.sin(production_al))

print("Aggregations over ufunc outputs:")
print("Sum of exp:", np.round(sum_exp, 2))
print("Mean of sin:", np.round(mean_sin, 4))
print()

#broadcast-summary table
panel_tot_farm=np.sum(production_al,axis=2)
print("Panel total per farms",panel_tot_farm)
print()
max_per_farm = np.max(panel_tot_farm, axis=1)
any_below_40 = np.any(panel_tot_farm < 40, axis=1)
all_above_50 = np.all(panel_tot_farm > 50, axis=1)

print("Max per farm:", max_per_farm)
print("Any below 40:", any_below_40)
print("All above 50:", all_above_50)
print()

#Final KPIs
# Overall total of all farms
overall_total = np.sum(production_al)

# Peak hour info — find max value & its indices
peak_value = np.max(production_al)
peak_index = np.argmax(production_al)  # flattened index
farm_idx, panel_idx, hour_idx = np.unravel_index(peak_index, production_al.shape)

# Average per panel across all farms (mean over farms and hours)
average_per_panel = np.mean(production_al, axis=(0,2))  # shape (4,)

print("Final KPIs:")
print(f"Overall total production across all farms: {overall_total}")
print(f"Peak value: {peak_value} (Farm {farm_idx+1}, Panel {panel_idx+1}, Hour {hour_idx+1})")
print("Average per panel across all farms:", np.round(average_per_panel, 2))





[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
Shape of production data: (3, 4, 3)

Exponential family results:
exp-> shape: (3, 4, 3) , dtype:  float64
exmp1 -> first row:
  [[2.20254658e+04 1.62753791e+05 5.98731417e+04]
 [8.10208393e+03 5.98731417e+04 2.20254658e+04]
 [1.62753791e+05 4.42412392e+05 1.20260328e+06]
 [2.97995799e+03 1.09563316e+03 8.10208393e+03]]
log -> first row:
  [[2.30258509 2.48490665 2.39789527]
 [2.19722458 2.39789527 2.30258509]
 [2.48490665 2.56494936 2.63905733]
 [2.07944154 1.94591015 2.19722458]]
log10 -> first row:
  [[1.         1.07918125 1.04139269]
 [0.95424251 1.04139269 1.        ]
 [1.07918125 1.11394335 1.14612804]
 [0.90308999 0.84509804 0.95424251]]
log2 -> first row:
  [[3.32192809 3.5849625  3.45943162]
 [3.169925   3.45943162 3.32192809]
 [3.5849625  3.70043972 3.80735492]
 [3.         2.80735492 3.169925  ]]
Trigonometric famil

In [25]:
arr_np1=np.array([[[1,2,3],[4,5,6]],
                  [[34,45,56],[66,43,67]]])
print(arr_np1)
print(arr_np1.ndim)
print(arr_np1.size)
print(arr_np1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[34 45 56]
  [66 43 67]]]
3
12
(2, 2, 3)


In [17]:
a=np.array(42)
print(a.ndim)

0


In [24]:
zeroes=np.zeros((2,5))
print(zeroes)

ones=np.ones((3,4))
print(ones)

random_arr=np.random.random((4,2))
print(random_arr)

#identity matrix
id=np.eye(3,2)
print(id)

range_arr=np.arange(0,10,2)
print(range_arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.88059113 0.25967077]
 [0.09235108 0.20770161]
 [0.44647211 0.10500183]
 [0.78208773 0.19404926]]
[[1. 0.]
 [0. 1.]
 [0. 0.]]
[0 2 4 6 8]
